### PR TITLE
feat: making body parser optional and configurable.

### LINKED ISSUE #21: Custom response middleware without `body-parser`
As first discussed [here](https://github.com/muratcorlu/connect-api-mocker/issues/18#issuecomment-401046998), in version `1.3.5` there is a breaking change ([commit](https://github.com/muratcorlu/connect-api-mocker/commit/08d3b96d3d5af5c2f1d5169f35e3e91c99601894)) that affects custom response middleware.

[`body-parser`](https://github.com/expressjs/body-parser) was added before the custom middleware, which means that the request is consumed before it can reach the custom code. This means that the 'data' and 'end' request events are no longer called in the custom code. See this [issue](https://github.com/expressjs/body-parser/issues/296) for a better explanation.
Maybe revert to the old code (let the response unaltered) and add a config option to enable parsing the JSON body for you?

### PR DESCRIPTION
**Pull request by vudodov**
**This is a breaking change.**
I thought it kinda makes sense to move it as an optional configuration, switched off by default. However if you don't agree I'm happy to discuss.

Closes #21

### CODE REVIEW

**Comment by muratcorlu** [comment]
What about setting is `true` by default to make it backward compatible? And I think, most of the people using `body-parser` will be helpful on custom responses.

**Comment by vudodov** [comment]
Will do

**Comment by vudodov** [comment]
@muratcorlu as promised, made body-parser optional and enabled by default.

**Comment by muratcorlu** [comment]
Thanks @vudodov. Merged it a new version on its way.

**Pull request merged**
