### PR TITLE
Unlocked usage of all parsers and options of `body-parser`

### PR DESCRIPTION
**Pull request by vudodov**
Since `body-parser` is default go to tool for parsing request body, it makes sense to unlock its full power with support of all available parsers and options.

### CODE REVIEW

**Comment by muratcorlu** [comment]
Looks great, thank you! Only thing is we need to mention this capability in Readme file before publishing a new version. I can try to write it in the evening or you are very welcome to add :)

**Comment by muratcorlu** [comment]
Do you also think to give a chance to completely disable `body-parser` regarding to #21 discussion?

**Comment by vudodov** [comment]
@muratcorlu sure, I'll do it in a separate PR, later next week.

**Comment by muratcorlu** [comment]
There is something wrong with Travis :/

**Comment by muratcorlu** [comment]
Can you try removing `cache` part from `.travis.yml`

```yml
cache:
  directories:
    - ~/.npm
```

**Comment by vudodov** [comment]
@muratcorlu I've added a bit of documentation in Readme. Feel free to change it or word it differently. I will try to make `body-parser` optional tmrw, but as a part of separate PR.

Not sure why build started to fail, doesn't seem like code-related issue. Could you please try re-run it, I don't have permissions.

And much appreciate for quick feedback

Thanks, Val :)

**Comment by vudodov** [comment]
Doesn't seem to help, I'll try to re-gen `package-lock.json`

**Comment by vudodov** [comment]
Doesn't seem like cache or code-base problem.
Looks like something to do with package-lock.json 🤔 
https://github.com/travis-ci/travis-ci/issues/10113

**Comment by vudodov** [comment]
In order to proof the theory I've added [this travis config](https://github.com/muratcorlu/connect-api-mocker/pull/38/commits/8376c481c3a4eb5c661e058c6ac1ad61bb70ca43).
It looks like failing build was caused by execution of `npm ci` which is executed if `package-lock.json` file is found.
As a workaround, I've forced `npm install`.

**Comment by muratcorlu** [comment]
Thank you @vudodov!

**Pull request merged**
