### PR TITLE
Logging of mocked requests

### PR DESCRIPTION
**Pull request by iakovmarkov**
Hi!
We've started using you lib at Ataccama and came up with a nifty little feature - logging of what request have been mocked by middleware, so it would be more transparent. It looks like this:

image

I think that it will remove the guesswork of "did this get passed to API?" and "does our mock layer work?".

### CODE REVIEW

**Comment by muratcorlu** [comment]
Thanks for your contribution. That seems great. But I would prefer to add that functionality with an optional parameter. So user could define that he/she wants some detailed logs or not.

Also that can fix issue #5

**Comment by iakovmarkov** [comment]
You're right, this should be optional. I'll think about it and will update my PR.

**Comment by iakovmarkov** [comment]
@muratcorlu check it out now.

**Comment by muratcorlu** [comment]
Giving option for custom logging function is great idea. Thanks, I'll merge and deploy it with a minor release.

**Pull request merged**
